input {
  beats {
    port => 5044
  }
}

filter {
  # Parse JSON string if it was not parsed in Filebeat
  if [message] =~ /^\{/ {
    json {
      source => "message"
    }
  }
  
  # Inject pipeline timestamp if missing
  if ![timestamp] {
    mutate {
      add_field => { "timestamp" => "%{@timestamp}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "omnicivilization-logs-%{+YYYY.MM.dd}"
  }
  
  # Keep stdout debug prints enabled for testing console
  stdout {
    codec => rubydebug
  }
}
